configure.ac: add AC_SEARCH_LIBS routine for libpcre
Somehow it fixes linking glib-2.0 during a cross compile.

Before this addition make failed like this:

/usr/lib/gcc-cross/arm-linux-gnueabihf/5/../../../../arm-linux-gnueabihf/bin/ld:
/data/george/images/beta/raspbian/rootfs/usr/lib/arm-linux-gnueabihf/libglib-2.0.a(libglib_2_0_la-gregex.o):
undefined reference to symbol 'pcre_study'
/data/george/images/beta/raspbian/rootfs/lib/arm-linux-gnueabihf/libpcre.so.3:
error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
M

Configured as follows:

./configure  CC=./sysroot-gcc CXX=./sysroot-g++ --prefix=/usr
--build=x86_64-linux-gnu --host=arm-linux-gnueabihf